baseURL = 'https://rybkr.com/'
languageCode = 'en-us'
title = 'Ryan Baker'
theme = "PaperMod"
publishDir = "docs"

[outputs]
home = ["HTML", "JSON"]

[markup]
  [highlight]
    codeFences = true
    lineNos = true
    noClasses = false
    guessSyntax = true
    style = ""

[params]
  ShowCodeCopyButtons = true

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 1

[[menu.main]]
name = "Teaching"
url = "/teaching/"
weight = 2

[[menu.main]]
name = "Resume"
url = "/resume/"
weight = 3

[[menu.main]]
name = "About"
url = "/about/"
weight = 4
