baseURL = 'https://rybkr.com/'
languageCode = 'en-us'
title = 'Ryan Baker'
theme = "PaperMod"
publishDir = "docs"

[outputs]
home = ["HTML"]

[markup]
  [highlight]
    codeFences = true
    lineNos = true
    noClasses = false
    guessSyntax = true
    style = ""

[params]
  ShowCodeCopyButtons = true
